name: ESP-IDF build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_esp32_v4_4:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: ESP-IDF v4.4 build esp32
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
    - name: ESP-IDF v4.4 build esp32s2
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s2
        command: 'idf.py set-target esp32s2 build'
    - name: ESP-IDF v4.4 build esp32s3
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s3
        command: 'idf.py set-target esp32s3 build'
